## **Loading the dataset**

In [44]:
import pandas as pd
df=pd.read_csv("/content/sample_data/Manchester United.csv")
df.head()

,Date,Opponent,Is_Home,Result,Goals,Opponent_Goals,Possession,Shots,Shots_On_Target,Passes_Completed,...,Opponent_Corners,Opponent_Crosses,Opponent_Fouls,Opponent_Offsides,Shot_Efficiency,Season,Month,Day_of_Week,Last5_Avg_Goals,Last5_Win_Rate
0,2013-08-26 22:00:00,Chelsea,1,0,0,0,55,12,3,463,...,1,4,10,1,0.250000,2013,8,1,0.000000,0.00
1,2013-09-17 21:45:00,Bayer Leverkusen,1,1,4,2,57,16,5,496,...,6,4,10,0,0.312500,2013,9,2,2.000000,0.50
2,2013-09-22 18:00:00,Manchester City,0,-1,1,4,58,14,3,417,...,8,6,8,1,0.214286,2013,9,7,1.666667,0.33
3,2013-10-02 21:45:00,Shakhtar Donetsk,0,0,1,1,50,12,5,342,...,3,2,11,0,0.416667,2013,10,3,1.500000,0.25
4,2013-10-23 21:45:00,Real Sociedad,1,1,1,0,55,18,5,394,...,4,1,14,1,0.277778,2013,10,3,1.400000,0.40

## **Encoding opponent column and saving the encoder**

In [45]:
import pickle #for saving model
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Opponent']=le.fit_transform(df['Opponent'])
#saving model
pickle.dump(le,open('encoder.pkl','wb'))

## **Separating features and target**

In [46]:
feature_cols = [
    "Opponent",
    "Is_Home",
    "Season",
    "Month",
    "Day_of_Week",
    "Last5_Avg_Goals",
    "Last5_Win_Rate",
]
X=df[feature_cols]
Y=df['Result']

# Save feature order for later
with open("features.pkl", "wb") as f:
    pickle.dump(feature_cols, f)

## **Train_Test_Split**

In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

## **Training the model**

In [48]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200,random_state=42)
model.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

## **Evaluate**

In [49]:
from sklearn.metrics import accuracy_score,classification_report
y_pred=model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

0.55
              precision    recall  f1-score   support

          -1       0.48      0.31      0.38        35
           0       0.38      0.17      0.23        30
           1       0.59      0.81      0.68        75

    accuracy                           0.55       140
   macro avg       0.48      0.43      0.43       140
weighted avg       0.52      0.55      0.51       140

In [50]:
df_error=pd.DataFrame({'Actual':Y_test,'Predicted':y_pred})
df_error

     Actual  Predicted
310       1          1
172       1          1
260      -1          1
594       0         -1
418       1          0
..      ...        ...
445       1         -1
548       1         -1
183       0          1
492       1          1
681       0         -1

[140 rows x 2 columns]

## **Saving the model**

In [51]:
pickle.dump(model,open('model.pkl','wb'))